theme: minima
title: Prajwal's static Site
author: Prajwal Bhetwal
email: prajwal@i-motor.com.au
description: > # this means to ignore newlines until "baseurl:"
Meta description

# social links
twitter_username: this.prajwal
github_username:  ypraxoc

show_excerpts: true # set to false to remove excerpts on the homepage
